//
//  z80defs.c
//  z80dis
//
//  Created by mark on 27/11/2018.
//  Copyright © 2018 Garetech. All rights reserved.
//

#include "z80dis.h"

inst_t cb00[] = {
    { 0x00, "RLC B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x01, "RLC C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x02, "RLC D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x03, "RLC E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x04, "RLC H"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x05, "RLC L"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x06, "RLC (HL)"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x07, "RLC A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x08, "RRC B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x09, "RRC C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0a, "RRC D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0b, "RRC E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0c, "RRC H"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0d, "RRC L"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0e, "RRC (HL)"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0f, "RRC A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x10, "RL B"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x11, "RL C"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x12, "RL D"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x13, "RL E"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x14, "RL H"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x15, "RL L"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x16, "RL (HL)"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x17, "RL A"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x18, "RR B"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x19, "RR C"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1a, "RR D"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1b, "RR E"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1c, "RR H"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1d, "RR L"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1e, "RR (HL)"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1f, "RR A"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x20, "SLA B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x21, "SLA C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x22, "SLA D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x23, "SLA E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x24, "SLA H"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x25, "SLA L"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x26, "SLA (HL)"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x27, "SLA A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x28, "SRA B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x29, "SRA C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2a, "SRA D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2b, "SRA E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2c, "SRA H"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2d, "SRA L"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2e, "SRA (HL)"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2f, "SRA A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x30, "SLL B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x31, "SLL C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x32, "SLL D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x33, "SLL E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x34, "SLL H"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x35, "SLL L"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x36, "SLL (HL)"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x37, "SLL A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x38, "SRL B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x39, "SRL C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3a, "SRL D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3b, "SRL E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3c, "SRL H"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3d, "SRL L"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3e, "SRL (HL)"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3f, "SRL A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x40, "BIT 0,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x41, "BIT 0,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x42, "BIT 0,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x43, "BIT 0,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x44, "BIT 0,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x45, "BIT 0,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x46, "BIT 0,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x47, "BIT 0,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x48, "BIT 1,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x49, "BIT 1,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4a, "BIT 1,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4b, "BIT 1,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4c, "BIT 1,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4d, "BIT 1,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4e, "BIT 1,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4f, "BIT 1,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x50, "BIT 2,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x51, "BIT 2,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x52, "BIT 2,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x53, "BIT 2,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x54, "BIT 2,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x55, "BIT 2,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x56, "BIT 2,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x57, "BIT 2,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x58, "BIT 3,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x59, "BIT 3,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5a, "BIT 3,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5b, "BIT 3,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5c, "BIT 3,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5d, "BIT 3,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5e, "BIT 3,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5f, "BIT 3,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x60, "BIT 4,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x61, "BIT 4,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x62, "BIT 4,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x63, "BIT 4,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x64, "BIT 4,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x65, "BIT 4,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x66, "BIT 4,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x67, "BIT 4,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x68, "BIT 5,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x69, "BIT 5,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6a, "BIT 5,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6b, "BIT 5,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6c, "BIT 5,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6d, "BIT 5,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6e, "BIT 5,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6f, "BIT 5,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x70, "BIT 6,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x71, "BIT 6,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x72, "BIT 6,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x73, "BIT 6,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x74, "BIT 6,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x75, "BIT 6,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x76, "BIT 6,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x77, "BIT 6,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x78, "BIT 7,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x79, "BIT 7,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7a, "BIT 7,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7b, "BIT 7,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7c, "BIT 7,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7d, "BIT 7,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7e, "BIT 7,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7f, "BIT 7,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x80, "RES 0,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x81, "RES 0,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x82, "RES 0,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x83, "RES 0,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x84, "RES 0,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x85, "RES 0,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x86, "RES 0,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x87, "RES 0,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x88, "RES 1,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x89, "RES 1,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8a, "RES 1,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8b, "RES 1,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8c, "RES 1,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8d, "RES 1,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8e, "RES 1,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8f, "RES 1,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x90, "RES 2,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x91, "RES 2,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x92, "RES 2,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x93, "RES 2,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x94, "RES 2,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x95, "RES 2,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x96, "RES 2,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x97, "RES 2,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x98, "RES 3,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x99, "RES 3,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9a, "RES 3,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9b, "RES 3,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9c, "RES 3,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9d, "RES 3,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9e, "RES 3,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9f, "RES 3,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa0, "RES 4,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa1, "RES 4,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa2, "RES 4,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa3, "RES 4,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa4, "RES 4,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa5, "RES 4,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa6, "RES 4,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa7, "RES 4,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa8, "RES 5,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa9, "RES 5,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xaa, "RES 5,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xab, "RES 5,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xac, "RES 5,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xad, "RES 5,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xae, "RES 5,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xaf, "RES 5,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb0, "RES 6,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb1, "RES 6,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb2, "RES 6,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb3, "RES 6,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb4, "RES 6,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb5, "RES 6,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb6, "RES 6,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb7, "RES 6,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb8, "RES 7,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb9, "RES 7,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xba, "RES 7,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbb, "RES 7,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbc, "RES 7,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbd, "RES 7,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbe, "RES 7,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbf, "RES 7,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc0, "SET 0,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc1, "SET 0,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc2, "SET 0,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc3, "SET 0,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc4, "SET 0,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc5, "SET 0,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc6, "SET 0,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc7, "SET 0,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc8, "SET 1,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc9, "SET 1,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xca, "SET 1,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xcb, "SET 1,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xcc, "SET 1,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xcd, "SET 1,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xce, "SET 1,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xcf, "SET 1,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd0, "SET 2,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd1, "SET 2,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd2, "SET 2,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd3, "SET 2,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd4, "SET 2,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd5, "SET 2,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd6, "SET 2,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd7, "SET 2,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd8, "SET 3,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd9, "SET 3,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xda, "SET 3,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xdb, "SET 3,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xdc, "SET 3,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xdd, "SET 3,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xde, "SET 3,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xdf, "SET 3,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe0, "SET 4,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe1, "SET 4,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe2, "SET 4,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe3, "SET 4,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe4, "SET 4,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe5, "SET 4,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe6, "SET 4,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe7, "SET 4,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe8, "SET 5,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe9, "SET 5,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xea, "SET 5,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xeb, "SET 5,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xec, "SET 5,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xed, "SET 5,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xee, "SET 5,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xef, "SET 5,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf0, "SET 6,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf1, "SET 6,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf2, "SET 6,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf3, "SET 6,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf4, "SET 6,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf5, "SET 6,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf6, "SET 6,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf7, "SET 6,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf8, "SET 7,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf9, "SET 7,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xfa, "SET 7,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xfb, "SET 7,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xfc, "SET 7,H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xfd, "SET 7,L"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xfe, "SET 7,(HL)" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xff, "SET 7,A"    , "", 2, atnon , atnon , (inst_t *) NULL }
};

inst_t ddcb[] = {   // ddcb and fdcb
    { 0x00, "*LD B,RLC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x01, "*LD C,RLC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x02, "*LD D,RLC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x03, "*LD E,RLC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x04, "*LD H,RLC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x05, "*LD L,RLC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x06, "RLC (%s)"       , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x07, "*LD A,RLC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x08, "*LD B,RRC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x09, "*LD C,RRC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x0a, "*LD D,RRC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x0b, "*LD E,RRC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x0c, "*LD H,RRC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x0d, "*LD L,RRC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x0e, "RRC (%s)"         , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x0f, "*LD A,RRC (%s)"   , "", 3, atidxd, atnon ,(inst_t *) NULL },
    { 0x10, "*LD B,RL (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x11, "*LD C,RL (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x12, "*LD D,RL (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x13, "*LD E,RL (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x14, "*LD H,RL (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x15, "*LD L,RL (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x16, "RL (%s)"          , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x17, "*LD A,RL (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x18, "*LD B,RR (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x19, "*LD C,RR (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x1a, "*LD D,RR (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x1b, "*LD E,RR (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x1c, "*LD H,RR (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x1d, "*LD L,RR (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x1e, "RR (%s)"          , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x1f, "*LD A,RR (%s)"    , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x20, "*LD B,SLA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x21, "*LD C,SLA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x22, "*LD D,SLA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x23, "*LD E,SLA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x24, "*LD H,SLA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x25, "*LD L,SLA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x26, "SLA (%s)"         , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x27, "*LD A,SLA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x28, "*LD B,SRA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x29, "*LD C,SRA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x2a, "*LD D,SRA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x2b, "*LD E,SRA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x2c, "*LD H,SRA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x2d, "*LD L,SRA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x2e, "SRA (%s)"         , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x2f, "*LD A,SRA (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x30, "*LD B,SLL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x31, "*LD C,SLL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x32, "*LD D,SLL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x33, "*LD E,SLL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x34, "*LD H,SLL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x35, "*LD L,SLL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x36, "SLL (%s)"         , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x37, "*LD A,SLL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x38, "*LD B,SRL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x39, "*LD C,SRL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x3a, "*LD D,SRL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x3b, "*LD E,SRL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x3c, "*LD H,SRL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x3d, "*LD L,SRL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x3e, "SRL (%s)"         , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x3f, "*LD A,SRL (%s)"   , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x40, "*BIT 0,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x41, "*BIT 0,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x42, "*BIT 0,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x43, "*BIT 0,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x44, "*BIT 0,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x45, "*BIT 0,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x46, "BIT 0,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x47, "*BIT 0,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x48, "*BIT 1,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x49, "*BIT 1,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x4a, "*BIT 1,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x4b, "*BIT 1,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x4c, "*BIT 1,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x4d, "*BIT 1,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x4e, "BIT 1,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x4f, "*BIT 1,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x50, "*BIT 2,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x51, "*BIT 2,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x52, "*BIT 2,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x53, "*BIT 2,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x54, "*BIT 2,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x55, "*BIT 2,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x56, "BIT 2,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x57, "*BIT 2,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x58, "*BIT 3,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x59, "*BIT 3,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x5a, "*BIT 3,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x5b, "*BIT 3,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x5c, "*BIT 3,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x5d, "*BIT 3,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x5e, "BIT 3,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x5f, "*BIT 3,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x60, "*BIT 4,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x61, "*BIT 4,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x62, "*BIT 4,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x63, "*BIT 4,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x64, "*BIT 4,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x65, "*BIT 4,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x66, "BIT 4,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x67, "*BIT 4,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x68, "*BIT 5,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x69, "*BIT 5,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x6a, "*BIT 5,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x6b, "*BIT 5,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x6c, "*BIT 5,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x6d, "*BIT 5,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x6e, "BIT 5,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x6f, "*BIT 5,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x70, "*BIT 6,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x71, "*BIT 6,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x72, "*BIT 6,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x73, "*BIT 6,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x74, "*BIT 6,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x75, "*BIT 6,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x76, "BIT 6,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x77, "*BIT 6,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x78, "*BIT 7,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x79, "*BIT 7,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x7a, "*BIT 7,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x7b, "*BIT 7,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x7c, "*BIT 7,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x7d, "*BIT 7,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x7e, "BIT 7,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x7f, "*BIT 7,(%s)"      , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x80, "*LD B,RES 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x81, "*LD C,RES 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x82, "*LD D,RES 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x83, "*LD E,RES 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x84, "*LD H,RES 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x85, "*LD L,RES 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x86, "RES 0,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x87, "*LD A,RES 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x88, "*LD B,RES 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x89, "*LD C,RES 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x8a, "*LD D,RES 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x8b, "*LD E,RES 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x8c, "*LD H,RES 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x8d, "*LD L,RES 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x8e, "RES 1,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x8f, "*LD A,RES 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x90, "*LD B,RES 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x91, "*LD C,RES 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x92, "*LD D,RES 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x93, "*LD E,RES 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x94, "*LD H,RES 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x95, "*LD L,RES 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x96, "RES 2,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x97, "*LD A,RES 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x98, "*LD B,RES 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x99, "*LD C,RES 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x9a, "*LD D,RES 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x9b, "*LD E,RES 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x9c, "*LD H,RES 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x9d, "*LD L,RES 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x9e, "RES 3,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0x9f, "*LD A,RES 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa0, "*LD B,RES 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa1, "*LD C,RES 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa2, "*LD D,RES 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa3, "*LD E,RES 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa4, "*LD H,RES 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa5, "*LD L,RES 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa6, "RES 4,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa7, "*LD A,RES 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa8, "*LD B,RES 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xa9, "*LD C,RES 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xaa, "*LD D,RES 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xab, "*LD E,RES 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xac, "*LD H,RES 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xad, "*LD L,RES 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xae, "RES 5,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xaf, "*LD A,RES 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb0, "*LD B,RES 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb1, "*LD C,RES 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb2, "*LD D,RES 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb3, "*LD E,RES 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb4, "*LD H,RES 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb5, "*LD L,RES 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb6, "RES 6,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb7, "*LD A,RES 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb8, "*LD B,RES 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xb9, "*LD C,RES 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xba, "*LD D,RES 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xbb, "*LD E,RES 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xbc, "*LD H,RES 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xbd, "*LD L,RES 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xbe, "RES 7,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xbf, "*LD A,RES 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc0, "*LD B,SET 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc1, "*LD C,SET 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc2, "*LD D,SET 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc3, "*LD E,SET 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc4, "*LD H,SET 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc5, "*LD L,SET 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc6, "SET 0,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc7, "*LD A,SET 0,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc8, "*LD B,SET 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xc9, "*LD C,SET 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xca, "*LD D,SET 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xcb, "*LD E,SET 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xcc, "*LD H,SET 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xcd, "*LD L,SET 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xce, "SET 1,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xcf, "*LD A,SET 1,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd0, "*LD B,SET 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd1, "*LD C,SET 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd2, "*LD D,SET 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd3, "*LD E,SET 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd4, "*LD H,SET 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd5, "*LD L,SET 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd6, "SET 2,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd7, "*LD A,SET 2,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd8, "*LD B,SET 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xd9, "*LD C,SET 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xda, "*LD D,SET 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xdb, "*LD E,SET 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xdc, "*LD H,SET 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xdd, "*LD L,SET 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xde, "SET 3,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xdf, "*LD A,SET 3,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe0, "*LD B,SET 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe1, "*LD C,SET 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe2, "*LD D,SET 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe3, "*LD E,SET 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe4, "*LD H,SET 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe5, "*LD L,SET 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe6, "SET 4,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe7, "*LD A,SET 4,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe8, "*LD B,SET 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xe9, "*LD C,SET 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xea, "*LD D,SET 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xeb, "*LD E,SET 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xec, "*LD H,SET 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xed, "*LD L,SET 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xee, "SET 5,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xef, "*LD A,SET 5,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf0, "*LD B,SET 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf1, "*LD C,SET 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf2, "*LD D,SET 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf3, "*LD E,SET 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf4, "*LD H,SET 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf5, "*LD L,SET 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf6, "SET 6,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf7, "*LD A,SET 6,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf8, "*LD B,SET 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xf9, "*LD C,SET 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xfa, "*LD D,SET 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xfb, "*LD E,SET 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xfc, "*LD H,SET 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xfd, "*LD L,SET 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xfe, "SET 7,(%s)"       , "", 4, atidxd, atnon ,(inst_t *) NULL },
    { 0xff, "*LD A,SET 7,(%s)" , "", 4, atidxd, atnon ,(inst_t *) NULL }
};

inst_t ed00[] = {
    { 0x00, "bios_0_BOOT"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x01, "bios_1_WBOOT"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x02, "bios_2_CONST"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x03, "bios_3_CONIN"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x04, "bios_4_CONOUT"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x05, "bios_5_LIST"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x06, "bios_6_PUNCHAUXOUT" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x07, "bios_7_READER"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x08, "bios_8_HOME"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x09, "bios_9_SELDSK"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0A, "bios_10_SETTRK"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0B, "bios_11_SETSEC"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0C, "bios_12_SETDMA"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0D, "bios_13_READ"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0E, "bios_14_WRITE"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0F, "bios_15_LISTST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x10, "bios_16_SECTRAN"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x12, "bios_17_CONOST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x12, "bios_18_AUXIST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x13, "bios_19_AUXOST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x14, "bios_20_DEVTBL"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x15, "bios_21_DEVINI"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x16, "bios_22_DRVTBL"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x17, "bios_23_MULTIO"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x18, "bios_24_FLUSH"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x19, "bios_25_MOVE"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1A, "bios_26_TIME"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1B, "bios_27_SELMEM"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1C, "bios_28_SETBNK"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1D, "bios_29_XMOVE"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1E, "bios_30_USERF"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1F, "bios_31_RESERV1"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x20, "bios_32_RESERV2"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x21, "BDOS_9_C_WRITESTR", "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x22, "bios_34_RESERV4"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x23, "bios_35_RESERV5"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x24, "bios_36_RESERV6"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x25, "bios_37_RESERV7"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x26, "bios_38_RESERV8"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x27, "bios_39_RESERV9"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x28, "bios_40_RESERV10" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x29, "bios_41_RESERV11" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2A, "bios_42_RESERV12" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2B, "bios_43_RESERV13" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2C, "bios_44_RESERV14" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2D, "bios_45_RESERV15" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2E, "bios_46_RESERV16" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x2F, "bios_47_RESERV17" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x30, "bios_48_RESERV18" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x32, "bios_49_RESERV19" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x32, "bios_50_RESERV20" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x33, "bios_51_RESERV21" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x34, "bios_52_RESERV22" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x35, "bios_53_RESERV23" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x36, "bios_54_RESERV24" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x37, "bios_55_RESERV25" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x38, "bios_56_RESERV26" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x39, "bios_57_RESERV27" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3A, "bios_58_RESERV28" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3B, "bios_59_RESERV29" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3C, "bios_60_RESERV30" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3D, "bios_61_RESERV31" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3E, "bios_62_RESERV32" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3F, "bios_63_RESERV33" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x40, "IN B,(C)"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x42, "OUT (C),B"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x42, "SBC HL,BC"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x43, "LD (%s),BC"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x44, "NEG"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x45, "RETN"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x46, "IM 0"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x47, "LD I,A"           , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x48, "IN C,(C)"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x49, "OUT (C),C"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4a, "ADC HL,BC"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4b, "LD BC,(%s)"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x4c, "*NEG"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4d, "RETI"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4e, "loaddflg %s"      , "", 4, atnn  , atnon , (inst_t *) NULL }, // *IM * (0?)
    { 0x4f, "LD R,A"           , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x50, "IN D,(C)"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x52, "OUT (C),D"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x52, "SBC HL,DE"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x53, "LD (%s),DE"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x54, "*NEG"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x55, "*RETN"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x56, "IM 1"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x57, "LD A,I"           , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x58, "IN E,(C)"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x59, "OUT (C),E"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5a, "ADC HL,DE"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5b, "LD DE,(%s)"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x5c, "*NEG"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5d, "*RETI"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5e, "IM 2"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5f, "LD A,R"           , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x60, "IN H,(C)"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x62, "OUT (C),H"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x62, "SBC HL,HL"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x63, "LD (%s),HL"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x64, "*NEG"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x65, "*RETN"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x66, "loaddepth %s"     , "", 4, atnn  , atnon , (inst_t *) NULL }, // "*IM 0"
    { 0x67, "RRD"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x68, "IN L,(C)"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x69, "OUT (C),L"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6a, "ADC HL,HL"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6b, "LD HL,(%s)"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x6c, "*NEG"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6d, "*RETI"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x6e, "loadtrace %s"     , "", 4, atnn  , atnon , (inst_t *) NULL }, // "*IM * (0?)"
    { 0x6f, "RLD"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x70, "*IN X,(C)"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x72, "*OUT (C),0"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x72, "SBC HL,SP"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x73, "LD (%s),SP"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x74, "*NEG"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x75, "*RETN"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x76, "*IM 1"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x77, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x78, "IN A,(C)"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x79, "OUT (C),A"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7a, "ADC HL,SP"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7b, "LD SP,(%s)"       , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x7c, "*NEG"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7d, "*RETI"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7e, "*IM 2"            , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7f, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x80, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x82, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x82, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x83, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x84, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x85, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x86, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x87, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x88, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x89, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8a, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8b, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8c, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8d, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8e, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8f, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x90, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x92, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x92, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x93, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x94, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x95, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x96, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x97, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x98, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x99, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9a, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9b, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9c, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9d, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9e, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9f, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa0, "LDI"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa2, "CPI"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa2, "INI"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa3, "OUTI"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa4, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa5, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa6, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa7, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa8, "LDD"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa9, "CPD"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xaa, "IND"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xab, "OUTD"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xac, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xad, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xae, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xaf, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb0, "LDIR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb2, "CPIR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb2, "INIR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb3, "OTIR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb4, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb5, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb6, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb7, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb8, "LDDR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb9, "CPDR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xba, "INDR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbb, "OTDR"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbc, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbd, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbe, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbf, "*NOP"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC0, "BIOS-00-BOOT"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC2, "BIOS-01-WBOOT"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC2, "BIOS-02-CONST"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC3, "BIOS-03-CONIN"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC4, "BIOS-04-CONOUT"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC5, "BIOS-05-LIST"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC6, "BIOS-06-PUNCH"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC7, "BIOS-07-READER"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC8, "BIOS-08-HOME"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xC9, "BIOS-09-SELDSK"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xCA, "BIOS-0A-SETTRK"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xCB, "BIOS-0B-SETSEC"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xCC, "BIOS-0C-SETDMA"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xCD, "BIOS-0D-READ"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xCE, "BIOS-0E-WRITE"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xCF, "BIOS-0F-LISTST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD0, "BIOS-10-SECTRAN"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD2, "BIOS-11-CONOST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD2, "BIOS-12-AUXIST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD3, "BIOS-13-AUXOST"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD4, "BIOS-14-DEVTBL"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD5, "BIOS-15-DEVINI"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD6, "BIOS-16-DRVTBL"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD7, "BIOS-17-MULTIO"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD8, "BIOS-18-FLUSH"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xD9, "BIOS-19-MOVE"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xDA, "BIOS-1A-TIME"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xDB, "BIOS-1B-SELMEM"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xDC, "BIOS-1C-SETBNK"   , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xDD, "BIOS-1D-XMOVE"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xDE, "BIOS-1E-USERF"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xDF, "BIOS-1F-RESERV1"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE0, "BIOS-20-RESERV2"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE1, "BIOS-21-RESERV3"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE2, "UNKNOWN"          , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE3, "BIOS-22-RESERV4"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE4, "BIOS-23-RESERV5"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE5, "BIOS-24-RESERV6"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE6, "BIOS-25-RESERV7"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE7, "BIOS-26-RESERV8"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE8, "BIOS-27-RESERV9"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xE9, "BIOS-28-RESERV10" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xEA, "BIOS-29-RESERV11" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xEB, "BIOS-2A-RESERV12" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xEC, "BIOS-2B-RESERV13" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xED, "brk"              , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xEE, "dreg"             , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xEF, "BIOS-2E-RESERV16" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF0, "BIOS-2F-RESERV17" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF2, "BIOS-30-RESERV18" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF2, "BIOS-31-RESERV19" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF3, "BIOS-32-RESERV20" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF4, "BIOS-33-RESERV21" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF5, "BIOS-34-RESERV22" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF6, "BIOS-35-RESERV23" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF7, "BIOS-36-RESERV24" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF8, "BIOS-37-RESERV25" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xF9, "BIOS-38-RESERV26" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xFA, "BIOS-39-RESERV27" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xFB, "BIOS-3A-RESERV28" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xFC, "BIOS-3B-RESERV29" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xFD, "BIOS-3C-RESERV30" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xFE, "BIOS-3D-RESERV31" , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xFF, "BIOS-3E-RESERV32" , "", 2, atnon , atnon , (inst_t *) NULL }
};

inst_t ddfd00[] = {
    { 0x00, "NOP"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x01, "LD BC,%s"   , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x02, "LD (BC),A"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x03, "INC BC"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x04, "INC B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x05, "DEC B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x06, "LD B,%s"    , "", 3, atn   , atnon , (inst_t *) NULL },
    { 0x07, "RLCA"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x08, "EX AF,AF'"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x09, "ADD %s,BC"  , "", 2, atidx , atnon , (inst_t *) NULL },
    { 0x0a, "LD A,(BC)"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0b, "DEC BC"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0c, "INC C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0d, "DEC C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x0e, "LD C,%s"    , "", 3, atn   , atnon , (inst_t *) NULL },
    { 0x0f, "RRCA"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x10, "DJNZ %s"    , "", 3, ate   , atnon , (inst_t *) NULL },
    { 0x11, "LD DE,%s"   , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x12, "LD (DE),A"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x13, "INC DE"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x14, "INC D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x15, "DEC D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x16, "LD D,%s"    , "", 3, atn   , atnon , (inst_t *) NULL },
    { 0x17, "RLA"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x18, "JR %s"      , "", 3, ate   , atnon , (inst_t *) NULL },
    { 0x19, "ADD %s,DE"  , "", 2, atidx , atnon , (inst_t *) NULL },
    { 0x1a, "LD A,(DE)"  , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1b, "DEC DE"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1c, "INC E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1d, "DEC E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x1e, "LD E,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x1f, "RRA"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x20, "JR NZ,%s"   , "", 3, ate   , atnon , (inst_t *) NULL },
    { 0x21, "LD %s,%s"   , "", 4, atidx , atnn  , (inst_t *) NULL }, // LD IX,nn
    { 0x22, "LD (%s),%s" , "", 4, atnn  , atidx , (inst_t *) NULL }, // LD (nn),IX FD 22 nn nn
    { 0x23, "INC %s"     , "", 2, atidx , atnon , (inst_t *) NULL }, // INC IX
    { 0x24, "INC %sh"    , "", 2, atnon , atnon , (inst_t *) NULL }, // INC IXh
    { 0x25, "DEC %sh"    , "", 2, atnon , atnon , (inst_t *) NULL }, // DEC IXh
    { 0x26, "LD %sh,%s"  , "", 3, atidx , atn   , (inst_t *) NULL }, // LD IXh, n
    { 0x27, "DAA"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x28, "JR Z,%s"    , "", 3, ate   , atnon , (inst_t *) NULL },
    { 0x29, "ADD %s,%s"  , "", 2, atidx , atidx , (inst_t *) NULL }, // ADD IX,IX
    { 0x2a, "LD %s,(%s)" , "", 4, atidx , atnn  , (inst_t *) NULL }, // LD IX,(nn)
    { 0x2b, "DEC %s"     , "", 2, atidx , atnon , (inst_t *) NULL }, // DEC IX
    { 0x2c, "INC %sl"    , "", 2, atidx , atnon , (inst_t *) NULL }, // INC IXl
    { 0x2d, "DEC %sl"    , "", 2, atidx , atnon , (inst_t *) NULL }, // DEC IXl
    { 0x2e, "LD %sl,%s"  , "", 3, atidx , atn   , (inst_t *) NULL }, // LD IXl, n
    { 0x2f, "CPL"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x30, "JR NC,%s"   , "", 3, ate   , atnon , (inst_t *) NULL },
    { 0x31, "LD SP,%s"   , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x32, "LD (%s),A"  , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x33, "INC SP"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x34, "INC (%s)"   , "", 3, atidxd, atnon , (inst_t *) NULL }, // INC (IX+d)
    { 0x35, "DEC (%s)"   , "", 3, atidxd, atnon , (inst_t *) NULL }, // DEC (IX+d)
    { 0x36, "LD (%s),%s" , "", 4, atidxd, atn   , (inst_t *) NULL }, // LD  (IX+d), n
    { 0x37, "SCF"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x38, "JR C,%s"    , "", 3, ate   , atnon , (inst_t *) NULL },
    { 0x39, "ADD %s,SP"  , "", 2, atidx , atnon , (inst_t *) NULL }, // ADD IX,SP
    { 0x3a, "LD A,(%s)"  , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0x3b, "DEC SP"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3c, "INC A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3d, "DEC A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x3e, "LD A,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x3f, "CCF"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x40, "LD B,B"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x41, "LD B,C"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x42, "LD B,D"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x43, "LD B,E"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x44, "LD B,%sh"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD B,IXh
    { 0x45, "LD B,%sl"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD B,IXl
    { 0x46, "LD B,(%s)"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD B,(IX+d)
    { 0x47, "LD B,A"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x48, "LD C,B"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x49, "LD C,C"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4a, "LD C,D"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4b, "LD C,E"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x4c, "LD C,%sh"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD C,IXh
    { 0x4d, "LD C,%sl"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD C,IXl
    { 0x4e, "LD C,(%s)"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD C,(IX+d)
    { 0x4f, "LD C,A"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x50, "LD D,B"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x51, "LD D,C"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x52, "LD D,D"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x53, "LD D,E"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x54, "LD D,%sh"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD D,IXh
    { 0x55, "LD D,%sl"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD D,IXl
    { 0x56, "LD D,(%s)"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD D,(IX+d)
    { 0x57, "LD D,A"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x58, "LD E,B"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x59, "LD E,C"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5a, "LD E,D"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5b, "LD E,E"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x5c, "LD E,%sh"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD E,IXh
    { 0x5d, "LD E,%sl"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD E,IXl
    { 0x5e, "LD E,(%s)"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD E,(IX+d)
    { 0x5f, "LD E,A"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x60, "LD %sh,B"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXh, B
    { 0x61, "LD %sh,C"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXh, C
    { 0x62, "LD %sh,D"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXh, D
    { 0x63, "LD %sh,E"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXh, E
    { 0x64, "?LD H,%sh"  , "", 2, atidx , atnon , (inst_t *) NULL }, // LD H,IXh invalid in zmac
    { 0x65, "?LD H,%sl"  , "", 2, atidx , atnon , (inst_t *) NULL }, // LD H,IXl invalid in zmac
    { 0x66, "?LD H,(%s)" , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD H,(IX+d)
    { 0x67, "LD %sh,A"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXh, A
    { 0x68, "LD %sl,B"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXl, B
    { 0x69, "LD %sl,C"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXl, C
    { 0x6a, "LD %sl,D"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXl, D
    { 0x6b, "LD %sl,E"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXl, E
    { 0x6c, "?LD %sl,H"  , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXl, H invalid in zmac
    { 0x6d, "?LD %sl,L"  , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXl, L invalid in zmac
    { 0x6e, "LD L,(%s)"  , "", 3, atnon , atnon , (inst_t *) NULL }, // LD L,(IX+d)
    { 0x6f, "LD %sl,A"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD IXh, A
    { 0x70, "LD (%s),B"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD (IX+d),B
    { 0x71, "LD (%s),C"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD (IX+d),C
    { 0x72, "LD (%s),D"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD (IX+d),D
    { 0x73, "LD (%s),E"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD (IX+d),E
    { 0x74, "LD (%s),H"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD (IX+d),H
    { 0x75, "LD (%s),L"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD (IX+d),L
    { 0x76, "HALT"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x77, "LD (%s),A"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD (IX+d),A
    { 0x78, "LD A,B"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x79, "LD A,C"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7a, "LD A,D"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7b, "LD A,E"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x7c, "LD A,%sh"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD A,IXh
    { 0x7d, "LD A,%sl"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD A,IXl
    { 0x7e, "LD A,(%s)"  , "", 3, atidxd, atnon , (inst_t *) NULL }, // LD A,(IX+d)
    { 0x7f, "LD A,A"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x80, "ADD A,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x81, "ADD A,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x82, "ADD A,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x83, "ADD A,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x84, "ADD A,%sh"  , "", 2, atidx , atnon , (inst_t *) NULL }, // LD A, IXh
    { 0x85, "ADD A,%sl"  , "", 2, atidx , atnon , (inst_t *) NULL }, // LD A, IXl
    { 0x86, "ADD A,(%s)" , "", 3, atidxd, atnon , (inst_t *) NULL }, // ADD A,(IX+d)
    { 0x87, "ADD A,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x88, "ADC A,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x89, "ADC A,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8a, "ADC A,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8b, "ADC A,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x8c, "ADC A,%sh"  , "", 2, atidx , atnon , (inst_t *) NULL }, // ADC A,IXh
    { 0x8d, "ADC A,%sl"  , "", 2, atidx , atnon , (inst_t *) NULL }, // ADC A,IXl
    { 0x8e, "ADC A,(%s)" , "", 3, atidxd, atnon , (inst_t *) NULL }, // ADC A,(IX+d)
    { 0x8f, "ADC A,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x90, "SUB B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x91, "SUB C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x92, "SUB D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x93, "SUB E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x94, "SUB %sh"    , "", 2, atidx , atnon , (inst_t *) NULL }, // SUB IXh
    { 0x95, "SUB %sl"    , "", 2, atidx , atnon , (inst_t *) NULL }, // SUB IXl
    { 0x96, "SUB (%s)"   , "", 3, atidxd, atnon , (inst_t *) NULL }, // SUB (IX+d)
    { 0x97, "SUB A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x98, "SBC A,B"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x99, "SBC A,C"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9a, "SBC A,D"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9b, "SBC A,E"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0x9c, "SBC A,%sh"  , "", 2, atidx , atnon , (inst_t *) NULL }, // SBC A,IXh
    { 0x9d, "SBC A,%sl"  , "", 2, atidx , atnon , (inst_t *) NULL }, // SBC A,IXl
    { 0x9e, "SBC A,(%s)" , "", 3, atidxd, atnon , (inst_t *) NULL }, // SBC A,(IX+d)
    { 0x9f, "SBC A,A"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa0, "AND B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa1, "AND C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa2, "AND D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa3, "AND E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa4, "AND %sh"    , "", 2, atidx , atnon , (inst_t *) NULL }, // AND IXh
    { 0xa5, "AND %sl"    , "", 2, atidx , atnon , (inst_t *) NULL }, // AND IXl
    { 0xa6, "AND (%s)"   , "", 3, atnon , atnon , (inst_t *) NULL }, // AND (IX+d)
    { 0xa7, "AND A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa8, "XOR B"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xa9, "XOR C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xaa, "XOR D"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xab, "XOR E"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xac, "XOR %sh"    , "", 2, atidx , atnon , (inst_t *) NULL }, // XOR IXh
    { 0xad, "XOR %sl"    , "", 2, atidx , atnon , (inst_t *) NULL }, // XOR IXl
    { 0xae, "XOR (%s)"   , "", 3, atidxd, atnon , (inst_t *) NULL }, // XOR (IX+d)
    { 0xaf, "XOR A"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb0, "OR B"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb1, "OR C"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb2, "OR D"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb3, "OR E"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb4, "OR %sh"     , "", 2, atidx , atnon , (inst_t *) NULL }, // OR IXh
    { 0xb5, "OR %sl"     , "", 2, atidx , atnon , (inst_t *) NULL }, // OR IXl
    { 0xb6, "OR (%s)"    , "", 3, atidxd, atnon , (inst_t *) NULL }, // OR (IX+d)
    { 0xb7, "OR A"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb8, "CP B"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xb9, "CP C"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xba, "CP D"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbb, "CP E"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xbc, "CP %sh"     , "", 2, atidx , atnon , (inst_t *) NULL }, // CP IXh
    { 0xbd, "CP %sl"     , "", 2, atidx , atnon , (inst_t *) NULL }, // CP IXl
    { 0xbe, "CP (%s)"    , "", 3, atidxd, atnon , (inst_t *) NULL }, // CP (IX+d)
    { 0xbf, "CP A"       , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc0, "RET NZ"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc1, "POP BC"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc2, "JP NZ,%s"   , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0xc3, "JP %s"      , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0xc4, "CALL NZ,%s" , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0xc5, "PUSH BC"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc6, "ADD A,%s"   , "", 3, atn   , atnon , (inst_t *) NULL },
    { 0xc7, "RST 0"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc8, "RET Z"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xc9, "RET"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xca, "JP Z,%s"    , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0xcb, "%s"         , "", 2, atgrp , atnon , cb00 },
    { 0xcc, "CALL Z,%s"  , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0xcd, "CALL %s"    , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0xce, "ADC A,%s"   , "", 3, atn   , atnon , (inst_t *) NULL },
    { 0xcf, "RST 8"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd0, "RET NC"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd1, "POP DE"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd2, "JP NC,%s"   , "", 4, atnn  , atnon , (inst_t *) NULL },
    { 0xd3, "OUT (%s),A" , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xd4, "CALL NC,%s" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xd5, "PUSH DE"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd6, "SUB %s"     , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xd7, "RST 10H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd8, "RET C"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xd9, "EXX"        , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xda, "JP C,%s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xdb, "IN A,(%s)"  , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xdc, "CALL C,%s"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xdd, "%s"         , "", 2, atgrp , atnon , ddfd00 },
    { 0xde, "SBC A,%s"   , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xdf, "RST 18H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe0, "RET PO"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe1, "POP %s"     , "", 2, atidx , atnon , (inst_t *) NULL }, // POP IX
    { 0xe2, "JP PO,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xe3, "EX (SP),%s" , "", 2, atidx , atnon , (inst_t *) NULL }, // EX (SP),IX
    { 0xe4, "CALL PO,%s" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xe5, "PUSH %s"    , "", 2, atidx , atnon , (inst_t *) NULL }, // PUSH IX
    { 0xe6, "AND %s"     , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xe7, "RST 20H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe8, "RET PE"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xe9, "JP (%s)"    , "", 2, atidx , atnon , (inst_t *) NULL }, // JP (IX)
    { 0xea, "JP PE,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xeb, "EX DE,%s"   , "", 2, atidx , atnon , (inst_t *) NULL }, // EX DE,IX
    { 0xec, "CALL PE,%s" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xed, "%s"         , "", 2, atgrp , atnon , ed00 },
    { 0xee, "XOR %s"     , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xef, "RST 28H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf0, "RET P"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf1, "POP AF"     , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf2, "JP P,%s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xf3, "DI"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf4, "CALL P,%s"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xf5, "PUSH AF"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf6, "OR %s"      , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xf7, "RST 30H"    , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf8, "RET M"      , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xf9, "LD SP,%s"   , "", 2, atidx , atnon , (inst_t *) NULL }, // LD SP, IX
    { 0xfa, "JP M,%s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xfb, "EI"         , "", 2, atnon , atnon , (inst_t *) NULL },
    { 0xfc, "CALL M,%s"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xfd, "%s"         , "", 2, atgrp , atnon ,  ddfd00 },
    { 0xfe, "CP %s"      , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xff, "RST 38H"    , "", 2, atnon , atnon , (inst_t *) NULL }
};



inst_t opsnormal[] = {
    { 0x00, "NOP"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x01, "LD BC,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x02, "LD (BC),A"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x03, "INC BC"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x04, "INC B"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x05, "DEC B"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x06, "LD B,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x07, "RLCA"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x08, "EX AF,AF'"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x09, "ADD HL,BC"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x0a, "LD A,(BC)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x0b, "DEC BC"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x0c, "INC C"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x0d, "DEC C"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x0e, "LD C,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x0f, "RRCA"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x10, "DJNZ %s"    , "", 2, ate   , atnon , (inst_t *) NULL },
    { 0x11, "LD DE,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x12, "LD (DE),A"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x13, "INC DE"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x14, "INC D"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x15, "DEC D"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x16, "LD D,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x17, "RLA"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x18, "JR %s"      , "", 2, ate   , atnon , (inst_t *) NULL },
    { 0x19, "ADD HL,DE"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x1a, "LD A,(DE)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x1b, "DEC DE"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x1c, "INC E"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x1d, "DEC E"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x1e, "LD E,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x1f, "RRA"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x20, "JR NZ,%s"   , "", 2, ate   , atnon , (inst_t *) NULL },
    { 0x21, "LD HL,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x22, "LD (%s),HL" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x23, "INC HL"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x24, "INC H"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x25, "DEC H"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x26, "LD H,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x27, "DAA"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x28, "JR Z,%s"    , "", 2, ate   , atnon , (inst_t *) NULL },
    { 0x29, "ADD HL,HL"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x2a, "LD HL,(%s)" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x2b, "DEC HL"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x2c, "INC L"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x2d, "DEC L"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x2e, "LD L,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x2f, "CPL"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x30, "JR NC,%s"   , "", 2, ate   , atnon , (inst_t *) NULL },
    { 0x31, "LD SP,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x32, "LD (%s),A"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x33, "INC SP"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x34, "INC (HL)"   , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x35, "DEC (HL)"   , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x36, "LD (HL),%s" , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x37, "SCF"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x38, "JR C,%s"    , "", 2, ate   , atnon , (inst_t *) NULL },
    { 0x39, "ADD HL,SP"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x3a, "LD A,(%s)"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0x3b, "DEC SP"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x3c, "INC A"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x3d, "DEC A"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x3e, "LD A,%s"    , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0x3f, "CCF"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x40, "LD B,B"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x41, "LD B,C"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x42, "LD B,D"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x43, "LD B,E"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x44, "LD B,H"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x45, "LD B,L"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x46, "LD B,(HL)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x47, "LD B,A"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x48, "LD C,B"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x49, "LD C,C"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x4a, "LD C,D"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x4b, "LD C,E"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x4c, "LD C,H"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x4d, "LD C,L"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x4e, "LD C,(HL)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x4f, "LD C,A"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x50, "LD D,B"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x51, "LD D,C"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x52, "LD D,D"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x53, "LD D,E"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x54, "LD D,H"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x55, "LD D,L"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x56, "LD D,(HL)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x57, "LD D,A"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x58, "LD E,B"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x59, "LD E,C"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x5a, "LD E,D"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x5b, "LD E,E"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x5c, "LD E,H"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x5d, "LD E,L"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x5e, "LD E,(HL)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x5f, "LD E,A"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x60, "LD H,B"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x61, "LD H,C"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x62, "LD H,D"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x63, "LD H,E"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x64, "LD H,H"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x65, "LD H,L"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x66, "LD H,(HL)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x67, "LD H,A"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x68, "LD L,B"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x69, "LD L,C"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x6a, "LD L,D"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x6b, "LD L,E"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x6c, "LD L,H"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x6d, "LD L,L"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x6e, "LD L,(HL)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x6f, "LD L,A"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x70, "LD (HL),B"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x71, "LD (HL),C"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x72, "LD (HL),D"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x73, "LD (HL),E"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x74, "LD (HL),H"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x75, "LD (HL),L"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x76, "HALT"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x77, "LD (HL),A"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x78, "LD A,B"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x79, "LD A,C"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x7a, "LD A,D"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x7b, "LD A,E"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x7c, "LD A,H"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x7d, "LD A,L"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x7e, "LD A,(HL)"  , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x7f, "LD A,A"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x80, "ADD A,B"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x81, "ADD A,C"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x82, "ADD A,D"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x83, "ADD A,E"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x84, "ADD A,H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x85, "ADD A,L"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x86, "ADD A,(HL)" , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x87, "ADD A,A"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x88, "ADC A,B"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x89, "ADC A,C"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x8a, "ADC A,D"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x8b, "ADC A,E"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x8c, "ADC A,H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x8d, "ADC A,L"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x8e, "ADC A,(HL)" , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x8f, "ADC A,A"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x90, "SUB B"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x91, "SUB C"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x92, "SUB D"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x93, "SUB E"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x94, "SUB H"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x95, "SUB L"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x96, "SUB (HL)"   , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x97, "SUB A"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x98, "SBC A,B"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x99, "SBC A,C"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x9a, "SBC A,D"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x9b, "SBC A,E"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x9c, "SBC A,H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x9d, "SBC A,L"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x9e, "SBC A,(HL)" , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0x9f, "SBC A,A"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa0, "AND B"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa1, "AND C"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa2, "AND D"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa3, "AND E"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa4, "AND H"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa5, "AND L"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa6, "AND (HL)"   , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa7, "AND A"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa8, "XOR B"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xa9, "XOR C"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xaa, "XOR D"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xab, "XOR E"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xac, "XOR H"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xad, "XOR L"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xae, "XOR (HL)"   , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xaf, "XOR A"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb0, "OR B"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb1, "OR C"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb2, "OR D"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb3, "OR E"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb4, "OR H"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb5, "OR L"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb6, "OR (HL)"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb7, "OR A"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb8, "CP B"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xb9, "CP C"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xba, "CP D"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xbb, "CP E"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xbc, "CP H"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xbd, "CP L"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xbe, "CP (HL)"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xbf, "CP A"       , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xc0, "RET NZ"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xc1, "POP BC"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xc2, "JP NZ,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xc3, "JP %s"      , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xc4, "CALL NZ,%s" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xc5, "PUSH BC"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xc6, "ADD A,%s"   , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xc7, "RST 0"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xc8, "RET Z"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xc9, "RET"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xca, "JP Z,%s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xcb, "%s"         , "", 1, atgrp , atnon , cb00 },
    { 0xcc, "CALL Z,%s"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xcd, "CALL %s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xce, "ADC A,%s"   , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xcf, "RST 8"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xd0, "RET NC"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xd1, "POP DE"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xd2, "JP NC,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xd3, "OUT (%s),A" , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xd4, "CALL NC,%s" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xd5, "PUSH DE"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xd6, "SUB %s"     , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xd7, "RST 10H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xd8, "RET C"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xd9, "EXX"        , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xda, "JP C,%s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xdb, "IN A,(%s)"  , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xdc, "CALL C,%s"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xdd, "%s"         , "", 1, atgrp , atnon , ddfd00 },
    { 0xde, "SBC A,%s"   , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xdf, "RST 18H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xe0, "RET PO"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xe1, "POP HL"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xe2, "JP PO,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xe3, "EX (SP),HL" , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xe4, "CALL PO,%s" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xe5, "PUSH HL"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xe6, "AND %s"     , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xe7, "RST 20H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xe8, "RET PE"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xe9, "JP (HL)"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xea, "JP PE,%s"   , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xeb, "EX DE,HL"   , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xec, "CALL PE,%s" , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xed, "%s"         , "", 1, atgrp , atnon , ed00 },
    { 0xee, "XOR %s"     , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xef, "RST 28H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xf0, "RET P"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xf1, "POP AF"     , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xf2, "JP P,%s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xf3, "DI"         , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xf4, "CALL P,%s"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xf5, "PUSH AF"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xf6, "OR %s"      , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xf7, "RST 30H"    , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xf8, "RET M"      , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xf9, "LD SP,HL"   , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xfa, "JP M,%s"    , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xfb, "EI"         , "", 1, atnon , atnon , (inst_t *) NULL },
    { 0xfc, "CALL M,%s"  , "", 3, atnn  , atnon , (inst_t *) NULL },
    { 0xfd, "%s"         , "", 1, atgrp , atnon , ddfd00 },
    { 0xfe, "CP %s"      , "", 2, atn   , atnon , (inst_t *) NULL },
    { 0xff, "RST 38H"    , "", 1, atnon , atnon , (inst_t *) NULL }
};


const char *reg8b[]={"b","c","d","e","h","l","(hl)","a"}; // (hl): (ix+d) (iy+d)

